"""empty message

Revision ID: 046ae7c7d0cc
Revises: 10fbb1c8bb61
Create Date: 2016-08-10 00:03:48.104985

"""

# revision identifiers, used by Alembic.
revision = '046ae7c7d0cc'
down_revision = '10fbb1c8bb61'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Doc', sa.Column('youtube_id', sa.String(), nullable=True))
    op.add_column('Sentence', sa.Column('aeneas_end', sa.Float(), nullable=True))
    op.add_column('Sentence', sa.Column('aeneas_start', sa.Float(), nullable=True))
    op.add_column('Sentence', sa.Column('manual_end', sa.Float(), nullable=True))
    op.add_column('Sentence', sa.Column('manual_start', sa.Float(), nullable=True))
    op.add_column('Sentence', sa.Column('youtube_id', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Sentence', 'youtube_id')
    op.drop_column('Sentence', 'manual_start')
    op.drop_column('Sentence', 'manual_end')
    op.drop_column('Sentence', 'aeneas_start')
    op.drop_column('Sentence', 'aeneas_end')
    op.drop_column('Doc', 'youtube_id')
    ### end Alembic commands ###
