"""empty message

Revision ID: 10fbb1c8bb61
Revises: 8bfc8a7e20cb
Create Date: 2016-07-22 03:39:04.244983

"""

# revision identifiers, used by Alembic.
revision = '10fbb1c8bb61'
down_revision = '8bfc8a7e20cb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('sentence', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sentence'], ['Sentence.id'], ),
    sa.ForeignKeyConstraint(['user'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Note')
    ### end Alembic commands ###
