"""empty message

Revision ID: 4862fb803e10
Revises: 046ae7c7d0cc
Create Date: 2016-10-15 19:39:53.019299

"""

# revision identifiers, used by Alembic.
revision = '4862fb803e10'
down_revision = '046ae7c7d0cc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Token', sa.Column('corpus_freq', sa.Integer(), nullable=True))
    op.add_column('Token', sa.Column('doc_freq', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Token', 'doc_freq')
    op.drop_column('Token', 'corpus_freq')
    ### end Alembic commands ###
