"""empty message

Revision ID: 8752f86d1e89
Revises: c2936ba298a0
Create Date: 2018-10-29 22:53:38.504966

"""

# revision identifiers, used by Alembic.
revision = '8752f86d1e89'
down_revision = 'c2936ba298a0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Sentence', 'annotators')
    op.drop_column('User', 'is_admin')
    op.drop_column('User', 'is_super_admin')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('is_super_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('User', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('Sentence', sa.Column('annotators', postgresql.BYTEA(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
