"""empty message

Revision ID: 8ef1dabe6f18
Revises: f0a014aa3169
Create Date: 2017-04-21 09:49:43.312752

"""

# revision identifiers, used by Alembic.
revision = '8ef1dabe6f18'
down_revision = 'f0a014aa3169'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('is_super_admin', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'is_super_admin')
    ### end Alembic commands ###
