"""empty message

Revision ID: f0a014aa3169
Revises: f727fd07ea8d
Create Date: 2017-01-27 00:06:13.882695

"""

# revision identifiers, used by Alembic.
revision = 'f0a014aa3169'
down_revision = 'f727fd07ea8d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Token', sa.Column('gram_2', sa.String(), nullable=True))
    op.add_column('Token', sa.Column('gram_3', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Token', 'gram_3')
    op.drop_column('Token', 'gram_2')
    ### end Alembic commands ###
