"""empty message

Revision ID: fcda5927e58c
Revises: None
Create Date: 2016-07-01 22:43:37.733330

"""

# revision identifiers, used by Alembic.
revision = 'fcda5927e58c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Doc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('annotators', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Sentence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sentence', sa.Text(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('annotators', sa.PickleType(), nullable=True),
    sa.Column('doc', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doc'], ['Doc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Break',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Float(), nullable=False),
    sa.Column('sentence', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sentence'], ['Sentence.id'], ),
    sa.ForeignKeyConstraint(['user'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('punctuation', sa.Boolean(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('sentence', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sentence'], ['Sentence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Peak',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prom', sa.Float(), nullable=True),
    sa.Column('token', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['token'], ['Token.id'], ),
    sa.ForeignKeyConstraint(['user'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Peak')
    op.drop_table('Token')
    op.drop_table('Break')
    op.drop_table('Sentence')
    op.drop_table('User')
    op.drop_table('Doc')
    ### end Alembic commands ###
